MVCDemo/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDemo.Models;

namespace MVCDemo.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult HelloAjax()
        {
            return Content("Hello ikramlim", "text/plain");
        }
        public ActionResult Sum(int a, int b)
        {
            return Content((a + b).ToString(), "text/plain");
        }

        public ActionResult DisplayObject()
        {
            Product p1 = new Product("pr1", "Name 1", 1000);
            return Json(p1, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DisplayListObject()
        {
            List<Product> listProduct = new List<Product>();
            listProduct.Add(new Product("pr1", "Name 1", 1000));
            listProduct.Add(new Product("pr2", "Name 2", 2000));
            listProduct.Add(new Product("pr3", "Name 3", 3000));
            return Json(listProduct, JsonRequestBehavior.AllowGet);
        }
    }
}

MVCDemo/Views/Demo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.hello').click(function () {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("HelloAjax", "Demo")',
                    success: function (result) {
                        $('#result1').html(result);
                    }
                })
            });
            //using parameters
            $('.sum').click(function () {
                $.ajax({
                    type: 'GET',
                    data: {a:2, b:2},
                    url: '@Url.Action("Sum", "Demo")',
                    success: function (result) {
                        $('#result2').html(result);
                    }
                })
            });

            //Display a Object with JSON
            $('.displayObject').click(function () {
                $.ajax({
                    type: 'GET',
                    datatype: 'json',
                    contentType: 'application/json',
                    url: '@Url.Action("DisplayObject", "Demo")',
                    success: function (result) {
                        var s = 'Id: ' + result.Id + '<br> Name: ' +
                            result.Name + '<br>Price: ' + result.Price;
                        $('#result3').html(s);
                    }
                })
            });

            //Display List Object with JSON
            $('.displayListObject').click(function () {
                $.ajax({
                    type: 'GET',
                    datatype: 'json',
                    contentType: 'application/json',
                    url: '@Url.Action("DisplayListObject", "Demo")',
                    success: function (result) {
                        var s = '';
                        for (var i = 0; i < result.length; i++)
                             s += '<br>Id: ' + result[i].Id + '<br> Name: ' +
                            result[i].Name + '<br>Price: ' + result[i].Price +
                                 '<br> ===================';
                        $('#result4').html(s);
                    }
                })
            });
        });
    </script>
</head>
<body>

    <h3>Basic Ajax</h3>
    <a href="#" class="hello">Hello</a>
    <br />
    <div id="result1"></div>

    <h3>Using Parameters</h3>
    <a href="#" class="sum">Sum</a>
    <br />
    <div id="result2"></div>

    <h3>Using JSON display a Object</h3>
    <a href="#" class="displayObject">Display JSON</a>
    <br />
    <div id="result3"></div>

    <h3>Using JSON display List Object</h3>
    <a href="#" class="displayListObject">Display List Object</a>
    <br />
    <div id="result4"></div>

</body>
</html>